# Generated by Django 4.1.6 on 2023-02-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_store', '0002_alter_formdata_course_alter_formdata_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='department',
            field=models.ForeignKey(choices=[('Computer Science', 'Computer Science'), ('Commerce', 'Commerce'), ('Chemistry', 'Chemistry'), ('English', 'English')], on_delete=django.db.models.deletion.CASCADE, to='school_store.department'),
        ),
    ]
