# Generated by Django 4.1.6 on 2023-02-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_store', '0004_alter_course_department_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='course',
            field=models.ForeignKey(choices=[('B-TECH', 'B-TECH'), ('B.COM', 'B.COM'), ('BBA', 'BBA'), ('BCA', 'BCA')], on_delete=django.db.models.deletion.CASCADE, to='school_store.course'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='department',
            field=models.ForeignKey(choices=[('Computer Science', 'Computer Science'), ('Commerce', 'Commerce'), ('Chemistry', 'Chemistry'), ('English', 'English')], on_delete=django.db.models.deletion.CASCADE, to='school_store.department'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='materials',
            field=models.ManyToManyField(choices=[('Note book', 'Note book'), ('Pen', 'Pen'), ('Pencil', 'Pencil')], to='school_store.material'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='purpose',
            field=models.ForeignKey(choices=[('Enquiry', 'Enquiry'), ('Place_order', 'Place_order'), ('Cancel_order', 'Cancel_order'), ('Return', 'Return')], on_delete=django.db.models.deletion.CASCADE, to='school_store.purpose'),
        ),
    ]
